version: "3.8"
services:
  nginx:
    restart: always
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      network:
        ipv4_address: 172.18.0.11
  nodeserver:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      network:
        ipv4_address: 172.18.0.12
