version: "3.8"
services:
  nginx:
    restart: always
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      network:
        ipv4_address: 172.18.0.11
  nodeserver:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      network:
        ipv4_address: 172.18.0.12
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      network:
        ipv4_address: 172.18.0.13
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      network:
        ipv4_address: 172.18.0.14
    depends_on:
      - postgres
networks:
  network:
    ipam:
      config:
        - subnet: 172.18.0.0/16